CREATE DATABASE PRUEBA;
DROP DATABASE PRUEBA;
/*Commands completed successfully.

Completion time: 2022-10-31T09:27:44.5589488-06:00*/
--CREACION DE BASE DE DATOS CON CONFIGURACION
CREATE DATABASE UNIVERSIDAD
	ON PRIMARY
	(NAME='UNIVERSIDAD',FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERV\MSSQL\DATA\UNIVERSIDAD.MDF',SIZE=200MB,MAXSIZE=500MB,FILEGROWTH=25%)
	LOG ON
	(NAME='UNIVERSIDAD_LOG',FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERV\MSSQL\DATA\UNIVERSIDAD_LOG.LDF',SIZE=100MB,MAXSIZE=250MB,FILEGROWTH=25%)

	USE UNIVERSIDAD;
	--CREACION DE ESQUEMA
	CREATE SCHEMA RRHH;
